import Head from "next/head"
import Menu from "./Menu"
import style from "../styles/Layout.module.css"
import ShoppingCart from "./ShoppingCart"

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>Git Merch { title ? `| ${ title }`: "" }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <div className={ style.container }>
        { children }
      </div>

      <ShoppingCart />

    </div>
  )
}

export default Layout